export const EMOTIONS = [
  { value: "cut off", label: "Cut-off" },
  { value: "happy", label: "Happy" },
  { value: "scared", label: "Scared" },
  { value: "anxious", label: "Anxious" },
  { value: "loving", label: "Loving" },
  { value: "driven", label: "Driven" },
  { value: "afraid", label: "Afraid" },
  { value: "uneasy", label: "Uneasy" },
  { value: "worried", label: "Worried" },
  { value: "fearful", label: "Fearful" },
  { value: "terrified", label: "Terrified" },
  { value: "angry", label: "Angry" },
  { value: "sad", label: "Sad" },
  { value: "hopeful", label: "Hopeful" },
  { value: "exhausted", label: "Exhausted" },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
];
