export const SENSATIONS = [
  { value: "present", label: "Present" },
  { value: "loose", label: "Loose" },
  { value: "excited", label: "Excited" },
  { value: "tender", label: "Tender" },
  { value: "clenched jaw", label: "Clenched Jaw" },
  { value: "nauseated", label: "Nauseated" },
  { value: "nervous", label: "Nervous" },
  { value: "restless", label: "Restless" },
  { value: "preoccupied", label: "Preoccupied" },
  { value: "racing", label: "Mind Racing" },
  { value: "tense", label: "Tense" },
  { value: "awake", label: "Awake" },
  { value: "fatigued", label: "Fatigued" },
  { value: "heavy", label: "Heavy" },
  { value: "alert", label: "Alert" },
  { value: "weak", label: "Weak" },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
];
